apiVersion: apps/v1
kind: Deployment
metadata: 
  name: pb-web
  labels: 
    app: pb-web
    type: pb-services
  namespace: pb-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pb-web
  template: 
    metadata:
      labels:
        app: pb-web
    spec:
      containers:
      - name: pb-web
        image: sreeramsunkara/pb-web-app
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            cpu: 0.2
            memory: "500Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: pb-web
  labels:
    app: pb-web
  namespace: pb-demo
spec:
  type: NodePort
  selector:
    app: pb-web
  ports:
  - name: http
    port: 8080
    targetPort: 8080

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pb-web-ingress
  namespace: pb-demo
spec:
  rules:
  - host: pb-web
    http:
      paths:
      - path: /
        backend:
          serviceName: pb-web
          servicePort: 8080
