pivotal:
  accountsService:
    name: accounts-service
  portfolioService:
    name: portfolio-service
  quotesService:
    name: quotes-service
  userService:
    name: user-service
  analyticsService:
    name: analytics-service