pivotal:
  accountsService:
    name: pb-accounts
  portfolioService:
    name: pb-portfolio
  quotesService:
    name: pb-quotes
  userService:
    name: pb-user
  analyticsService:
    name: pb-analytics
  summary:
    quotes: 3
    symbols:
      it: VMW,IBM,GOOG,AMD,HPQ,CSCO,AAPL
      fs: JPM,C,MS,BAC,GS,WFC,BK


spring:
  application:
    name: web-service

logging:
  level:
    io:
      pivotal: DEBUG
    org:
      springframework:
        web: WARN
        cloud: WARN
management:
  endpoints:
    web:
      exposure:
        include: "*"